<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Atividade;

class AtividadeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $atividades = [
            [
                'titulo' => 'Estudar Laravel Framework',
                'categoria' => 'Estudos',
                'tags' => ['laravel', 'php', 'framework', 'backend'],
                'descricao' => 'Aprender os conceitos básicos do framework Laravel, incluindo rotas, controllers, models e migrations',
                'status' => 'em_andamento',
                'data_inicio' => now(),
                'data_fim' => now()->addDays(7),
                'prioridade' => 3,
                'tempo_estimado' => 480, // 8 horas
                'tempo_real' => 240, // 4 horas
                'progresso' => 50,
                'local' => 'Casa',
                'url' => 'https://laravel.com/docs',
                'notas' => 'Focar em Eloquent ORM e Blade templates',
                'lembrete' => now()->addDays(1)->setTime(9, 0),
                'repeticao' => 'nenhuma',
                'privada' => false,
                'favorita' => true,
                'cor' => '#3B82F6',
                'icone' => 'book-open',
                'meta' => 'Dominar Laravel básico',
                'energia' => 4,
                'urgencia' => 3,
                'importancia' => 5,
            ],
            [
                'titulo' => 'Fazer exercícios físicos',
                'categoria' => 'Saúde',
                'tags' => ['exercícios', 'saúde', 'bem-estar'],
                'descricao' => 'Praticar exercícios físicos por 30 minutos incluindo cardio e musculação',
                'status' => 'pendente',
                'data_inicio' => now(),
                'data_fim' => now()->addDays(1),
                'prioridade' => 2,
                'tempo_estimado' => 30,
                'progresso' => 0,
                'local' => 'Academia',
                'repeticao' => 'diaria',
                'privada' => false,
                'favorita' => false,
                'cor' => '#10B981',
                'icone' => 'dumbbell',
                'meta' => 'Manter forma física',
                'energia' => 3,
                'urgencia' => 2,
                'importancia' => 4,
            ],
            [
                'titulo' => 'Ler documentação PHP 8.3',
                'categoria' => 'Estudos',
                'tags' => ['php', 'documentação', 'programação'],
                'descricao' => 'Estudar as novas funcionalidades do PHP 8.3 e melhorar conhecimentos',
                'status' => 'pendente',
                'data_inicio' => now(),
                'data_fim' => now()->addDays(3),
                'prioridade' => 2,
                'tempo_estimado' => 120,
                'progresso' => 0,
                'local' => 'Casa',
                'url' => 'https://www.php.net/manual/en/',
                'repeticao' => 'nenhuma',
                'privada' => false,
                'favorita' => false,
                'cor' => '#8B5CF6',
                'icone' => 'code',
                'meta' => 'Atualizar conhecimentos PHP',
                'energia' => 2,
                'urgencia' => 2,
                'importancia' => 3,
            ],
            [
                'titulo' => 'Organizar workspace de desenvolvimento',
                'categoria' => 'Organização',
                'tags' => ['organização', 'produtividade', 'workspace'],
                'descricao' => 'Limpar e organizar a área de trabalho, arquivos e projetos',
                'status' => 'concluida',
                'data_inicio' => now()->subDays(1),
                'data_fim' => now(),
                'prioridade' => 1,
                'tempo_estimado' => 60,
                'tempo_real' => 45,
                'progresso' => 100,
                'local' => 'Casa',
                'repeticao' => 'semanal',
                'privada' => false,
                'favorita' => false,
                'cor' => '#F59E0B',
                'icone' => 'folder-open',
                'meta' => 'Manter ambiente organizado',
                'energia' => 1,
                'urgencia' => 1,
                'importancia' => 2,
            ],
            [
                'titulo' => 'Reunião com equipe de desenvolvimento',
                'categoria' => 'Trabalho',
                'tags' => ['reunião', 'equipe', 'projeto'],
                'descricao' => 'Reunião semanal para alinhamento de projetos e definição de próximos passos',
                'status' => 'pendente',
                'data_inicio' => now()->addDays(2),
                'data_fim' => now()->addDays(2),
                'prioridade' => 3,
                'tempo_estimado' => 60,
                'progresso' => 0,
                'local' => 'Escritório',
                'url' => 'https://meet.google.com/abc-defg-hij',
                'lembrete' => now()->addDays(2)->setTime(8, 30),
                'repeticao' => 'semanal',
                'privada' => false,
                'favorita' => false,
                'cor' => '#EF4444',
                'icone' => 'users',
                'meta' => 'Manter equipe alinhada',
                'energia' => 2,
                'urgencia' => 4,
                'importancia' => 4,
            ],
            [
                'titulo' => 'Criar portfólio pessoal',
                'categoria' => 'Projetos Pessoais',
                'tags' => ['portfólio', 'frontend', 'carreira'],
                'descricao' => 'Desenvolver um portfólio pessoal com React e TypeScript',
                'status' => 'pendente',
                'data_inicio' => now()->addDays(5),
                'data_fim' => now()->addDays(14),
                'prioridade' => 2,
                'tempo_estimado' => 1200, // 20 horas
                'progresso' => 0,
                'local' => 'Casa',
                'url' => 'https://github.com/meu-portfolio',
                'repeticao' => 'nenhuma',
                'privada' => false,
                'favorita' => true,
                'cor' => '#06B6D4',
                'icone' => 'briefcase',
                'meta' => 'Mostrar habilidades técnicas',
                'energia' => 3,
                'urgencia' => 2,
                'importancia' => 4,
            ],
            [
                'titulo' => 'Estudar metodologias ágeis',
                'categoria' => 'Estudos',
                'tags' => ['agile', 'scrum', 'metodologia'],
                'descricao' => 'Aprofundar conhecimentos em Scrum, Kanban e outras metodologias ágeis',
                'status' => 'pendente',
                'data_inicio' => now()->addDays(7),
                'data_fim' => now()->addDays(21),
                'prioridade' => 1,
                'tempo_estimado' => 600, // 10 horas
                'progresso' => 0,
                'local' => 'Casa',
                'url' => 'https://www.scrum.org/',
                'repeticao' => 'nenhuma',
                'privada' => false,
                'favorita' => false,
                'cor' => '#84CC16',
                'icone' => 'lightbulb',
                'meta' => 'Melhorar gestão de projetos',
                'energia' => 2,
                'urgencia' => 1,
                'importancia' => 3,
            ],
        ];

        foreach ($atividades as $atividade) {
            Atividade::create($atividade);
        }
    }
} 