sonar.projectKey=jotavtech_dashmeboard
sonar.organization=jotavtech
sonar.projectName=Dashmeboard
sonar.projectVersion=0.1.0

sonar.sources=frontend/src,backend/src
sonar.tests=frontend/src,backend/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.config.js,**/*.config.ts,**/*.d.ts

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.typescript.tsconfigPaths=frontend/tsconfig.json,backend/tsconfig.json

sonar.sourceEncoding=UTF-8
